spring:
   
   datasource:
      username: sneakers   
      password: sneakers
      url: jdbc:mysql://localhost:3306/sneakers
         
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
     
   
     
         
               

